### Creates a new patinet
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Juan Gomez",
  "email": "jgomez7@example.com",
  "address": "789 Willow St, Springfield",
  "dateOfBirth": "2000-10-17",
  "registeredDate": "2025-06-06"
}
###